apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: "labdroid-tower"
    name: "labdroid-tower"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "labdroid-tower:latest"
    resources: {}
    source:
      git:
        ref: master
        uri: https://gogs-labdroid.apps.home.labdroid.net/green/labdroid-tower.git
      contextDir:
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        from:
          kind: DockerImage
          name: ansible-tower-34/ansible-tower
        forcePull: true
      type: Docker
kind: List
metadata: {}
